// This file was AUTOMATICALLY GENERATED by dbg-import (smuggol) for github.com/robertkrimen/dbg

package parser

import (
	Dbg "github.com/pptang/goodtime/go/goodtime/otto/dbg"
)

var dbg, dbgf = Dbg.New()
